### ISSUE TITLE
Server Crash on Block Placement

### ISSUE THREAD

**Issue by Err0r202** [LunaPixelStudios/Better-MC#1360] opened 2023-08-18 18:50 UTC
### Describe the Bug

When you place a betterend:flavolie_slab on the ground the server instantls crashed. 
Thes blocks also generate normaly in the end and dont have a texturte 

### Reproduction Steps

1.get a flavolite_slab
2.place it
3.server crash

### Screenshots and Videos

![2023-08-18_20 49 18](https://github.com/LunaPixelStudios/Better-MC/assets/96497313/caadfe4d-bf14-414a-9ec1-99e4fb5b0f60)

### Operating System

Ubuntu 22.1

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

9.5

### Other Mods

chunky

**Comment by Err0r202** [comment] 2023-08-18 19:00
I further reserched that problem and came to the conclusion that the vertical slab mod is the problem because every slab you place crahsed the server

**Comment by muon-rw** [comment] 2023-08-19 01:35
To fix this issue you can download the latest release from https://github.com/Andrew6rant/Auto-Slabs/releases/ 

It will be included in a future update, but 1.1.1 is not yet available on CurseForge.

**Comment by muon-rw** [comment] 2023-08-19 01:40
The missing textures on some vertical slabs are due to BCLib using a nonstandard model/texture format. I submitted a compatibility request which you can track here: https://github.com/Andrew6rant/Auto-Slabs/issues/13

**Closed** 2023-08-20 18:55 UTC
Labels: bug, fabric

**Comment by rbutera** [comment] 2023-08-24 11:16
why is this closed as completed? the issue is still in the game. shouldn't this only be closed once the fix is included in the mod pack?

**Comment by muon-rw** [comment] 2023-08-24 15:06
> why is this closed as completed? the issue is still in the game. shouldn't this only be closed once the fix is included in the mod pack?

GitHub is used for development tracking, and this issue is fixed in the in-dev version of the modpack. Rest assured there will be a release soon
