### ISSUE TITLE
Server completely crashing

### ISSUE THREAD

**Issue by Chr1s70ph** [LunaPixelStudios/Better-MC#1568] opened 2024-02-13 09:11 UTC
### Describe the Bug

I usually get this about once a day, and I'm not sure what causes it.
I suspect that the Exception in `netty pipeline` has something to do with it, but im not sure.

Full error-log is attached via link

### Reproduction Steps

1. Run Server with Service file

/etc/systemd/system/server.service 
```
[Unit]
Description=Starts the server
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/home/ubuntu/martins_homework/start.sh
WorkingDirectory=/home/ubuntu/martins_homework
User=ubuntu

# Restart the server when it is stopped or crashed after 30 seconds
# Comment out RestartSec if you want to restart immediately
Restart=always
RestartSec=30

# StandardInput=null

[Install]
WantedBy=multi-user.target
```

2. Sudden random crash

### Crash Report or Log

`Service Logs`
https://gist.github.com/Chr1s70ph/f4b60db04cbcf094e947151dd31c8fd7

`Crash Logs`
- https://gist.github.com/Chr1s70ph/52cfbf2e868882bc0091226bc5c58980
- https://gist.github.com/Chr1s70ph/8e917224bea701dab6d23135346dda8a

### Operating System

Ubuntu 22.04.3 LTS

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc 1.19.2 v20

### Other Mods

`none`

**Comment by Chr1s70ph** [comment] 2024-02-13 09:14
I will gladly provide more information if needed

**Comment by chorbintime** [comment] 2024-02-16 03:57
Please send the crash report

Feb 12 22:50:43 instance-20230728-0024 start.sh[61692]: [22:50:43] [Server Watchdog/ERROR]: This crash report has been saved to: /home/ubuntu/martins_homework/./crash-reports/crash-2024-02-12_22.50.43-server.txt

**Comment by Chr1s70ph** [comment] 2024-02-16 15:03
> Please send the crash report
> 
> Feb 12 22:50:43 instance-20230728-0024 start.sh[61692]: [22:50:43] [Server Watchdog/ERROR]: This crash report has been saved to: /home/ubuntu/martins_homework/./crash-reports/crash-2024-02-12_22.50.43-server.txt

I have added the output to my issue. See `Crash Logs` gist.

**Comment by chorbintime** [comment] 2024-02-20 07:14
Can you recreate the crash and send a 2nd crash report? It appears to be an issue with the Thermoo mod, but the developer said that it could be another mod causing it, and a 2nd report may help.

**Comment by Chr1s70ph** [comment] 2024-02-20 09:53
> Can you recreate the crash and send a 2nd crash report? It appears to be an issue with the Thermoo mod, but the developer said that it could be another mod causing it, and a 2nd report may help.

I've got nine crash reports total. Appended the latest one to my issue now.

**Comment by chorbintime** [comment] 2024-02-24 14:30
Originally thought it was an issue with the Thermoo mod, but the developer said they'd need more crash reports to verify for sure. 

This is what they said just now. My suggestion would be to wait until the next modpack update, and hope the issue is somehow fixed by us updating the mods in the modpack. Your world may also just be corrupted - who knows. I'm sorry that there isn't a more concrete solution to this.
![image](https://github.com/LunaPixelStudios/Better-MC/assets/112908845/e43f1ff0-f3a3-404c-a1df-60d1be02e42d)

**Closed by chorbintime** 2024-02-24 14:30 UTC
Labels: bug, fabric
