### ISSUE TITLE
Empty or non-existent pool: minecraft:witch_hut/foundation causing server crashes when near structure

### ISSUE THREAD

**Issue by AstroLive0** [LunaPixelStudios/Better-MC#1593] opened 2024-03-09 03:44 UTC
### Describe the Bug

[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation
[03:35:40] [Worker-Main-9/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool: minecraft:witch_hut/foundation

when attempting to load chunks near or at a pillager outpost, completely kills chunkloading and crashes server

### Reproduction Steps

1. host a server and join it
2. locate a pillager outpost (for me it i just tried to locate frozen peaks)
3. sit there in confusion as your server crashes and floods your console with "Empty or non-existent pool: minecraft:witch_hut/foundation"

...
 

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

### Other Mods

nop

**Comment by muon-rw** [comment] 2024-03-09 08:25
This is caused by Dungeons and Taverns, which isn’t in v26. I would recommend reinstalling a fresh version of the server pack and transferring over only your world folder.

**Comment by Miniluchi** [comment] 2024-03-11 08:09
Hello, i have the same problem here, removing Dungeons and Taverns solved the bug? Any alternative to keep the mod ?

**Comment by AstroLive0** [comment] 2024-03-11 08:12
It does kind of solve the issue, there isnt really an alternative right now but ive asked the mod developer to fix the issue for 1.20.1, as they have fixed it for 1.20.4

**Closed** 2024-03-11 08:16 UTC
Labels: bug, forge

**Comment by Miniluchi** [comment] 2024-03-11 08:25
Thanks you for the advices, i will try to update all mods from server.
Btw, how do you check your TPS ?

**Comment by AstroLive0** [comment] 2024-03-11 08:50
I use Spark Profiler, which comes with the server pack; run /spark profiler start
wait how ever much time you would like and then run /spark profiler stop
what ive been doing is starting it, playing the server w my friends and then after around 15 minutes i stop the profiler, it will output with a link you can go to which will tell you a lot of stats including RAM usage, CPU usage, TPS, and things like which mods are taking up the ticks (fyi if it says neruina is taking up a lot, ignore this as thats just how the mod works, it isnt actually taking up anything)

**Comment by Miniluchi** [comment] 2024-03-11 09:07
Ok il will check that, thanks you ! 😊
