### ISSUE TITLE
Shulker Dupe bug

### ISSUE THREAD

**Issue by DarkexSS** [LunaPixelStudios/Better-MC#773] opened 2022-10-02 20:41 UTC
### Describe the Bug

After breaking a shulker with a guy taking a object of it, the object will still in the shulker but the guy stills having the object, so, dupe.

### Reproduction Steps

1. A User takes a object of a shulker
2. You break the shulker after he taked the object
3. Put/check the shulker and the object will be in his inventory and in the shulker

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Fabric v7.5

### Optifine

No

**Comment by KuronishiX** [comment] 2022-10-04 04:41
I was able to recreate this after some time, because the reproduction steps from OP wasn't very clear due to the slight language barrier. No harm done, just took a little bit longer.

I was going to attach a video but my laptop struggles with recording... However if you need it, I am able to make a video when I have access to my PC.

The reproduction steps are as follow:

Notes: I believe this dupe can only be replicated with 2 accounts or a friend, unless there is a tech mod that can break a block and place a block in Better MC.
 
1. Place down a shulker box and put the items inside that you want to dupe.

2. Player 1 will open the shulker box UI.

3. Player 2 will destroy the shulker box while Player 1 still has the shulker's UI open.
    Upon breaking the shulker box, Player 1 should still be inside the shulker's UI.

5. Player 1 will now take the items from the shulker box and into Player 1's inventory and close the shulker's UI.
    Player 2 can now place the shulker box back down.

6. If done correctly, the items that Player 1 has taken out will still be inside the shulker box, thus duping the items.

To replicate this perfectly, just leave the items INSIDE the shulker box until it is broken.
I will also warn you that you DO NOT put any items inside the bugged shulker box's UI, as it will delete the items when you close it.

I am not sure if there is a mod that's causing this to happen, But the most 'simple?' fix I can think of is just making the UI force close when the shulker box is destroyed.

**Comment by xSHXRKIEx** [comment] 2022-10-07 08:48
Thanks for the report we will look into it

**Closed** 2022-10-21 10:22 UTC
Labels: bug, fabric
